### ISSUE TITLE
Make a compiled version available

### ISSUE THREAD

**Issue by davestewart** [martinbean/bootstrap-3-card#2]
Hey Martin.

Is there a compiled version available to just drop into an existing project?

**Comment by martinbean** [comment]
@davestewart Not at the minute, but could add one. The idea is more to use it as a LESS component though.

**Comment by nandoblanco** [comment]
I'd also be interested in a compiled version...

**Comment by martinbean** [comment]
Closing this Issue as this project a Sass component, to be dropped into a Sass project and compiled. It doesn’t really make sense to offer a “compiled” version, otherwise people will be including multiple stylesheets in their websites and web applications.

**Comment by Firestorm-Graphics** [comment]
erm don't you mean sass ? atlas thats the files provided are
